### ISSUE TITLE
Step 1 - Verify Orcid   (18 and 28)

### ISSUE THREAD

**Issue by withanage** [craft-oa/ui-library#1]
## TODO

- [x]  Change text:  You can choose to verify your ORCID iD or skip it. If you choose to skip it now, You can verify your ORCID iD from your profile section in OJS later.
- [x]   Verify ORCID iD should be blue
## Figma

https://www.figma.com/design/Wf7sDlUg2372jaKKTJ0Mgz/OJS-3.4-3.5?node-id=3086-5495&t=6UCuUUII39Qa8V02-4

![Image](https://github.com/craft-oa/ui-library/assets/1921992/4108f576-86b4-4eb2-ad61-b748b61f5d54)

###  Storybook

![Image](https://github.com/craft-oa/ui-library/assets/1921992/bfe05e84-f342-4adb-a15b-ded465eb8e2b)

**Comment by withanage** [comment]
- [ ]  Change text:  You can choose to verify your ORCID iD or skip it. If you choose to skip it now, You can verify your ORCID iD from your profile section in OJS later.
- [ ]
